version: '3.8'

services:
  db:
    image: postgres:16.0-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TIMELINE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TIMELINE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TIMELINE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
