version: '3.8'
name: "microservices"

volumes:
  mysqldb_data:

services:
  users-grpc:
    build:
      context: docker/app
    volumes:
      - ./protobuf:/protobuf
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/users
    ports:
      - "3000:${PORT}"
    environment:
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./.mysqldb_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    environment:
      - ADMINER_DEFAULT_SERVER=mysqldb
    env_file:
      - .env
    depends_on:
      - mysqldb

